module.exports = {
    People: [ {
            id: 1,
            name: "Luke Skywalker",
            mass: "175lbs",
            hair_color: "black",
            skin_color: "white",
            birth_year: "07.29.2021",
            gender: "male",
            species_id: 11,
            homeworld_id: 12,
            height: 172,
        },
    
        {
            id: 2,
            name: "Leia Organa",
            mass: "150lbs",
            hair_color: "red",
            skin_color: "black",
            birth_year: "07.31.2021",
            gender: "female",
            species_id: 21,
            homeworld_id: 22,
            height: 160,
        },
    
        {
            id: 3,
            name: "Owen Lars",
            mass: "165lbs",
            hair_color: "red",
            skin_color: "brown",
            birth_year: "07.31.2021",
            gender: "male",
            species_id: 31,
            homeworld_id: 32,
            height: 155,
        },
    
        {
            id: 4,
            name: "Biggs Darklighter",
            mass: "145lbs",
            hair_color: "red",
            skin_color: "white",
            birth_year: "07.31.2021",
            gender: "male",
            species_id: 31,
            homeworld_id: 32,
            height: 150,
        },
    ],
}