module.exports = {
    People: [ {
            id: 1,
            name: "Luke Skywalker",
			height: "172",
			mass: "77",
			hair_color: "blond",
			skin_color: "fair",
			eye_color: "blue",
			birth_year: "19BBY",
			gender: "male",
			homeworld: {name: "Tatooine", climate: "arid", population: "200000"},
        },
        {
            id: 2,
            // name: "Darth Vader",
			height: "202",
			mass: "136",
			hair_color: "none",
			skin_color: "white",
			eye_color: "yellow",
			birth_year: "41.9BBY",
			// gender: "male",
			homeworld: {name: "Tatooine", /*climate: "arid",*/ population: "200000"},
        },
        {
            id: 3,
            name: "Leia Organa",
			height: "150",
			mass: "49",
			hair_color: "brown",
			skin_color: "light",
			eye_color: "brown",
			birth_year: "19BBY",
			gender: "female",
			homeworld: {name: "Alderaan", climate: "temperate", population: "2000000000"},
        },
    
        {
            id: 4,
            name: "Owen Lars",
            height: "178",
			mass: "120",
			hair_color: "brown, grey",
			skin_color: "light",
			eye_color: "blue",
			birth_year: "52BBY",
			gender: "male",
			homeworld: {name: "Tatooine", climate: "arid", population: "200000"},
        },
    
        {
            id: 5,
            name: "Biggs Darklighter",
            mass: "145lbs",
            hair_color: "red",
            skin_color: "white",
            birth_year: "07.31.2021",
            gender: "male",
            species_id: 31,
            homeworld_id: {name: "Tatooine", climate: "arid", population: "200000"},
            height: 150,
        },
    ],
}